### PR TITLE
feat: restart flow, executor or gateway

### PR DESCRIPTION
**Pull request by subbuv26**
**Goal**

Restart
- [x] Flow
- [x] Executor
- [x] Gateway

- [x] Run [Integration tests GHA](https://github.com/jina-ai/jcloud/actions/workflows/integration-tests.yml) manually & comment the link. 👉 https://github.com/jina-ai/jcloud/actions/runs/3841234021 ✅

@jina-ai/team-wolf

### CODE REVIEW

**Comment by subbuv26** [comment]
Restart Flow
restart_flow

**Comment by subbuv26** [comment]
Restart Gateway
restart_gateway

**Comment by subbuv26** [comment]
Restart Executor
restart_executor

**Comment by subbuv26** [comment]
Restart Flow
restart_flow_1
restart_flow_2

**Comment by subbuv26** [comment]
Restart Gateway
restart_gateway_1
restart_gateway_2

**Comment by subbuv26** [comment]
Restart Executor
restart_executor_1
restart_executor_2

**Review by zac-li — APPROVED** [review]

**Pull request merged**
